name: CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build and run tests
    runs-on: macOS-latest
    
    steps:
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.0.0
      with:
        lane: 'build'
