name: CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build app
    runs-on: macOS-latest
    
    steps:
    - name: Bundle installl
      uses: "CultureHQ/actions-bundler@v1.0.0"
        
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.0.0
      with:
        lane: 'build'
