name: CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build app
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        gem install bundler
        gem update bundler
        bundle install --without development --jobs 4 --retry 3
        
    - name: Bundle installing...
      run: bundle install
         
    - name: Run building....
      uses: maierj/fastlane-action@v1.0.0
      with:
        lane: 'build'
