name: CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build app
    runs-on: macOS-latest
    
    steps:
    - name: Bundle installing...
      run: bundle install
         
    - name: Run building....
      uses: maierj/fastlane-action@v1.0.0
      with:
        lane: 'build'
