name: CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build app
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        gem install bundler
        gem update bundler
        bundle install --without development --jobs 4 --retry 3
        
    - name: Build application
      uses: maierj/fastlane-action@v1.0.0
      with:
        lane: 'build'
